version: '3.9'

services:
  mongodb:
    container_name: mongodb
    build: ./database
    ports:
      - "2727:27017"

  patient_mdb:
    container_name: patient_mdb
    build: ./
    ports:
      - "888:8082"
    depends_on:
      - mongodb
    environment:
      spring.data.mongodb.uri: "mongodb://mongodb:27017/MediscreenDatabase"