version: '3.9'

services:
  mongo_db:
    container_name: mongo_db
    build: ./database
    ports:
      - "2727:27017"

  patient_mdb:
    container_name: patient_mdb
    build: ./
    ports:
      - "888:8082"
    depends_on:
      - mongo_db
    environment:
      spring.data.mongodb.uri: "mongodb://mongo_db:27017/MediscreenDatabase"