db.Notes.insertMany(
[
  {
    "_id":{"$oid":"6478a8463421bbb5fd86fd9d"},
    "lastname":"TestNone",
    "notes":"Patientstatesthattheyare'feelingterrific'Noneatorbelowrecommendedlevel",
    "patId":1
  },
  {
    "_id":{"$oid":"6478a8463421bbb5fd86fd9e"},
    "lastname":"TestBorderline",
    "notes":"PatientstatesthattheyarefeelingagreatdealofstressatworkPatientalsocomplainsthattheirhearingseemsAbnormalasoflate",
    "patId":2
  },
  {
    "_id":{"$oid":"6478a8463421bbb5fd86fd9f"},
    "lastname":"TestBorderline",
    "notes":"PatientstatesthattheyhavehadaReactiontomedicationwithinlast3monthsPatientalsocomplainsthattheirhearingcontinuestobeproblematic",
    "patId":2
  },
  {
    "_id":{"$oid":"6478a8463421bbb5fd86fda0"},
    "lastname":"TestInDanger",
    "notes":"PatientstatesthattheyareshorttermSmoker",
    "patId":3
  },
  {
    "_id":{"$oid":"6478a8463421bbb5fd86fda1"},
    "lastname":"TestInDanger",
    "notes":"PatientstatesthattheyquitwithinlastyearPatientalsocomplainsthatofAbnormalbreathingspellsLabreportsCholesterolLDLhigh",
    "patId":3
  },
  {
    "_id":{"$oid":"6478a8463421bbb5fd86fda2"},
    "lastname":"TestEarlyOnset",
    "notes":"PatientstatesthatwalkingupstairshasbecomedifficultPatientalsocomplainsthattheyarehavingshortnessofbreathLabresultsindicateAntibodiespresentelevatedReactiontomedication",
    "patId":4
  },
  {
    "_id":{"$oid":"6478a8463421bbb5fd86fda3"},
    "lastname":"TestEarlyOnset",
    "notes":"Patientstatesthattheyareexperiencingbackpainwhenseatedforalongtime",
    "patId":4
  },
  {
    "_id":{"$oid":"6478a8463421bbb5fd86fda4"},
    "lastname":"TestEarlyOnset",
    "notes":"PatientstatesthattheyareashorttermSmokerHemoglobinA1Caboverecommendedlevel",
    "patId":4
  },
  {
    "_id":{"$oid":"6478a8463421bbb5fd86fda5"},
    "lastname":"TestEarlyOnset",
    "notes":"PatientstatesthatBodyHeight,BodyWeight,Cholesterol,DizzinessandReaction",
    "patId":4
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4504ffc"},
    "lastname":"Ferguson",
    "notes":"Lepatientdéclarequ'ilsesenttrèsbien\r\nPoidségalouinférieuraupoidsrecommandé",
    "patId":5
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4504ffd"},
    "lastname":"Ferguson",
    "notes":"Lepatientdéclarequ'ilsesentfatiguépendantlajournée\r\nIlseplaintégalementdedouleursmusculaires\r\nTestsdelaboratoireindiquantunemicroalbumineélevée",
    "patId":5
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4504ffe"},
    "lastname":"Ferguson",
    "notes":"Lepatientdéclarequ'ilnesesentpassifatiguéqueça\r\nFumeur,ilaarrêtédansles12moisprécédents\r\nTestsdelaboratoireindiquantquelesanticorpssontélevés",
    "patId":5
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4504fff"},
    "lastname":"Rees",
    "notes":"Lepatientdéclarequ'ilressentbeaucoupdestressautravail\r\nIlseplaintégalementquesonauditionestanormaledernièrement",
    "patId":6
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505000"},
    "lastname":"Rees",
    "notes":"Lepatientdéclareavoirfaituneréactionauxmédicamentsaucoursdes3derniersmois\r\nIlremarqueégalementquesonauditioncontinued'êtreanormale",
    "patId":6
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505001"},
    "lastname":"Rees",
    "notes":"Testsdelaboratoireindiquantunemicroalbumineélevée",
    "patId":6
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505002"},
    "lastname":"Rees",
    "notes":"Lepatientdéclarequetoutsembleallerbien\r\nLelaboratoirerapportequel'hémoglobineA1Cdépasseleniveaurecommandé\r\nLepatientdéclarequ’ilfumedepuislongtemps",
    "patId":6
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505003"},
    "lastname":"Arnold",
    "notes":"Lepatientdéclarequ'ilfumedepuispeu",
    "patId":7
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505004"},
    "lastname":"Arnold",
    "notes":"Testsdelaboratoireindiquantunemicroalbumineélevée",
    "patId":7
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505005"},
    "lastname":"Arnold",
    "notes":"Lepatientdéclarequ'ilestfumeuretqu'ilacessédefumerl'annéedernière\r\nIlseplaintégalementdecrisesd’apnéerespiratoireanormales\r\nTestsdelaboratoireindiquantuntauxdecholestérolLDLélevé",
    "patId":7
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505006"},
    "lastname":"Arnold",
    "notes":"TestsdelaboratoireindiquantuntauxdecholestérolLDLélevé",
    "patId":7
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505007"},
    "lastname":"Sharp",
    "notes":"Lepatientdéclarequ'illuiestdevenudifficiledemonterlesescaliers\r\nIlseplaintégalementd’êtreessoufflé\r\nTestsdelaboratoireindiquantquelesanticorpssontélevés\r\nRéactionauxmédicaments",
    "patId":8
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505008"},
    "lastname":"Sharp",
    "notes":"Lepatientdéclarequ'ilamalaudoslorsqu'ilresteassispendantlongtemps",
    "patId":8
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505009"},
    "lastname":"Sharp",
    "notes":"Lepatientdéclareavoircommencéàfumerdepuispeu\r\nHémoglobineA1Csupérieureauniveaurecommandé",
    "patId":8
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b450500a"},
    "lastname":"Ince",
    "notes":"Lepatientdéclareavoirdesdouleursaucouoccasionnellement\r\nLepatientremarqueégalementquecertainsalimentsontungoûtdifférent\r\nRéactionapparenteauxmédicaments\r\nPoidscorporelsupérieuraupoidsrecommandé",
    "patId":9
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b450500b"},
    "lastname":"Ince",
    "notes":"Lepatientdéclareavoireuplusieursépisodesdevertigedepuisladernièrevisite.\r\nTailleinclusedanslafourchetteconcernée",
    "patId":9
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b450500c"},
    "lastname":"Ince",
    "notes":"Lepatientdéclarequ'ilsouffreencorededouleurscervicalesoccasionnelles\r\nTestsdelaboratoireindiquantunemicroalbumineélevée\r\nFumeur,ilaarrêtédansles12moisprécédents",
    "patId":9
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b450500d"},
    "lastname":"Ince",
    "notes":"Lepatientdéclareavoireuplusieursépisodesdevertigedepuisladernièrevisite.\r\nTestsdelaboratoireindiquantquelesanticorpssontélevés",
    "patId":9
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b450500e"},
    "lastname":"Ross",
    "notes":"Lepatientdéclarequ'ilsesentbien\r\nPoidscorporelsupérieuraupoidsrecommandé",
    "patId":10
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b450500f"},
    "lastname":"Ross",
    "notes":"Lepatientdéclarequ'ilsesentbien",
    "patId":10
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505010"},
    "lastname":"Wilson",
    "notes":"Lepatientdéclarequ'ilseréveillesouventavecuneraideurarticulaire\r\nIlseplaintégalementdedifficultéspours’endormir\r\nPoidscorporelsupérieuraupoidsrecommandé\r\nTestsdelaboratoireindiquantuntauxdecholestérolLDLélevé",
    "patId":11
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505011"},
    "lastname":"Buckland",
    "notes":"Lestestsdelaboratoireindiquentquelesanticorpssontélevés\r\nHémoglobineA1Csupérieureauniveaurecommandé",
    "patId":12
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505012"},
    "lastname":"Clark",
    "notes":"Lepatientdéclareavoirdeladifficultéàseconcentrersursesdevoirsscolaires\r\nHémoglobineA1Csupérieureauniveaurecommandé",
    "patId":13
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505013"},
    "lastname":"Clark",
    "notes":"Lepatientdéclarequ'ils’impatientefacilementencasd’attenteprolongée\r\nIlsignaleégalementquelesproduitsdudistributeurautomatiquenesontpasbons\r\nTestsdelaboratoiresignalantdestauxanormauxdecellulessanguines",
    "patId":13
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505014"},
    "lastname":"Clark",
    "notes":"Lepatientsignalequ'ilestfacilementirritépardesbroutilles\r\nIldéclareégalementquel'aspirateurdesvoisinsfaittropdebruit\r\nTestsdelaboratoireindiquantquelesanticorpssontélevés",
    "patId":13
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505015"},
    "lastname":"Bailey",
    "notes":"Lepatientdéclarequ'iln'aaucunproblème",
    "patId":14
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505016"},
    "lastname":"Bailey",
    "notes":"Lepatientdéclarequ'iln'aaucunproblème\r\nTailleinclusedanslafourchetteconcernée\r\nHémoglobineA1Csupérieureauniveaurecommandé",
    "patId":14
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505017"},
    "lastname":"Bailey",
    "notes":"Lepatientdéclarequ'iln'aaucunproblème\r\nPoidscorporelsupérieuraupoidsrecommandé\r\nLepatientasignaléplusieursépisodesdevertigedepuissadernièrevisite",
    "patId":14
  },
  {
    "_id":{"$oid":"647f01dfaa98f5c8b4505018"},
    "lastname":"Bailey",
    "notes":"Lepatientdéclarequ'iln'aaucunproblème\r\nTestsdelaboratoireindiquantunemicroalbumineélevée",
    "patId":14
  }
]);



